### ISSUE TITLE
R version?

### ISSUE THREAD

**Issue by njbowen** [kegrinde/STEAM#2]
got this error, should I use higher or lower version? thanks.

> library(devtools)
Loading required package: usethis
> install_github("kegrinde/STEAM")
Downloading GitHub repo kegrinde/STEAM@master
Skipping 3 packages not available: gdsfmt, SNPRelate, SeqArray
Installing 4 packages: bootstrap, gdsfmt, SNPRelate, SeqArray
Installing packages into ‘/usr/local/lib/R/3.6/site-library’
(as ‘lib’ is unspecified)
Error: Failed to install 'STEAM' from GitHub:
  (converted from warning) packages ‘gdsfmt’, ‘SNPRelate’, ‘SeqArray’ are not available (for R version 3.6.1)

**Comment by kegrinde** [comment]
try installing the latest versions of the gdsfmt, SNPRelate, and SeqArray packages from Bioconductor:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("gdsfmt")
BiocManager::install("SNPRelate")
BiocManager::install("SeqArray")
```
